"""add user_id to categories

Revision ID: 9f38bc08b2dd
Revises: 
Create Date: 2025-01-28 16:37:13.210742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f38bc08b2dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('user_id', sa.String(), nullable=False))
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'])
    op.add_column('files', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'files', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'user_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_unique_constraint('categories_name_key', 'categories', ['name'])
    op.drop_column('categories', 'user_id')
    # ### end Alembic commands ###
